# Generated by Django 6.0.6 on 2026-07-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
