# Generated by Django 6.0.6 on 2026-06-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20, unique=True)),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(choices=[('booking_amount', 'Booking Amount'), ('advance', 'Advance Payment'), ('installment', 'Installment'), ('final', 'Final Payment'), ('refund', 'Refund')], max_length=20)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='payment_docs/')),
                ('transaction_slip', models.FileField(blank=True, null=True, upload_to='payment_docs/')),
                ('cheque_copy', models.FileField(blank=True, null=True, upload_to='payment_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
        ),
    ]
