# Generated by Django 6.0.6 on 2026-06-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cheque_copy',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='next_due_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_slip',
        ),
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], default='partial', max_length=20),
            preserve_default=False,
        ),
    ]
