# Generated by Django 6.0.6 on 2026-06-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_cheque_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], default='partial', max_length=20),
        ),
    ]
