# Generated by Django 6.0.6 on 2026-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
