# Generated by Django 6.0.6 on 2026-07-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_plot_id_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='facing',
            field=models.CharField(default='Not Assigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_size',
            field=models.CharField(default='Not Assigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='plot',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='projects.project'),
            preserve_default=False,
        ),
    ]
