# Generated by Django 6.0.6 on 2026-07-04 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('SA', 'Sales Advisor'), ('SO', 'Sales Officer'), ('ASM', 'Assistant Sales Manager'), ('SM', 'Sales Manager'), ('AGM', 'Assistant General Manager'), ('GM', 'General Manager'), ('DD', 'Deputy Director'), ('DIR', 'Director'), ('SD', 'Senior Director'), ('ED', 'Executive Director'), ('SED', 'Senior Executive Director'), ('VP', 'Vice President'), ('PRES', 'President'), ('MD', 'Managing Director'), ('CH', 'Chairman')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee'),
        ),
    ]
