# Generated by Django 5.2.6 on 2026-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('default_commission_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
