# Generated by Django 5.2.6 on 2026-07-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('forgot_username', 'Forgot Username'), ('forgot_password', 'Forgot Password')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
