# Generated by Django 5.2.6 on 2026-07-11 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternative_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='customer_docs/')),
                ('pan', models.FileField(blank=True, null=True, upload_to='customer_docs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='customer_docs/')),
                ('nominee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered')], default='pending', max_length=20)),
                ('ownership_status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('sale_status', models.CharField(choices=[('booked', 'Booked'), ('fully_paid', 'Fully Paid'), ('registered', 'Registered'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('payment_completed', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_property', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='customers.customer')),
                ('plot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='projects.plot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
            ],
        ),
    ]
