# Generated by Django 6.0.6 on 2026-06-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternative_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='customer_docs/')),
                ('pan', models.FileField(blank=True, null=True, upload_to='customer_docs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='customer_docs/')),
                ('nominee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='leads.lead')),
            ],
        ),
    ]
