# Generated by Django 6.0.6 on 2026-07-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_customer_booking_advance_amount_and_more'),
        ('customers', '0002_customer_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lead',
        ),
        migrations.AddField(
            model_name='customer',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ownership_status',
            field=models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
