# Generated by Django 6.0.6 on 2026-07-05 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_customer_booking_advance_amount_and_more'),
        ('customers', '0003_remove_customer_assigned_to_remove_customer_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookings.booking'),
        ),
    ]
