# Generated by Django 5.2.6 on 2026-07-11 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('registration_date', models.DateField()),
                ('registrar_office', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_deed_number', models.CharField(blank=True, max_length=100, null=True)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stamp_duty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sale_deed', models.FileField(blank=True, null=True, upload_to='registrations/')),
                ('registration_copy', models.FileField(blank=True, null=True, upload_to='registrations/')),
                ('ec_document', models.FileField(blank=True, null=True, upload_to='registrations/')),
                ('tax_receipt', models.FileField(blank=True, null=True, upload_to='registrations/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='registrations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='customers.customer')),
            ],
        ),
    ]
