# Generated by Django 6.0.6 on 2026-06-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registrar_office',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_file',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_status',
        ),
        migrations.AddField(
            model_name='registration',
            name='document_number',
            field=models.CharField(default='DOC-000', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='registrar_name',
            field=models.CharField(default='Default Registrar', max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_id',
            field=models.CharField(default='REG-000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
