# Generated by Django 6.0.6 on 2026-07-08 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_booking'),
        ('registrations', '0002_remove_registration_registrar_office_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registrar_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ec_document',
            field=models.FileField(blank=True, null=True, upload_to='registrations/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='registration',
            name='other_document',
            field=models.FileField(blank=True, null=True, upload_to='registrations/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registrar_office',
            field=models.CharField(default='Not Assigned', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_copy',
            field=models.FileField(blank=True, null=True, upload_to='registrations/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(default='REG000000', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='sale_deed',
            field=models.FileField(blank=True, null=True, upload_to='registrations/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='sale_deed_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='stamp_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='registration',
            name='tax_receipt',
            field=models.FileField(blank=True, null=True, upload_to='registrations/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
