# Generated by Django 5.2.6 on 2026-07-11 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('leads', '0001_initial'),
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_source', models.CharField(choices=[('lead', 'Lead'), ('walk_in', 'Walk-in'), ('reference', 'Reference'), ('online', 'Online')], default='walk_in', max_length=20)),
                ('booked_client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('demand_draft', 'Demand Draft')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_remarks', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('registered', 'Registered'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('workflow_status', models.CharField(choices=[('booked', 'Booked'), ('commission_ready', 'Commission Ready'), ('commission_generated', 'Commission Generated'), ('commission_paid', 'Commission Paid'), ('registered', 'Registered')], default='booked', max_length=30)),
                ('booking_form', models.FileField(blank=True, null=True, upload_to='booking_docs/')),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='booking_docs/')),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='booking_docs/')),
                ('pan', models.FileField(blank=True, null=True, upload_to='booking_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='employees.employee')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='teams.team')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='leads.lead')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
