# Generated by Django 6.0.6 on 2026-06-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_remarks', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('registered', 'Registered')], default='booked', max_length=20)),
                ('booking_form', models.FileField(blank=True, null=True, upload_to='booking_docs/')),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='booking_docs/')),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='booking_docs/')),
                ('pan', models.FileField(blank=True, null=True, upload_to='booking_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers.customer')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
