# Generated by Django 6.0.6 on 2026-07-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_customer_booking_advance_amount_and_more'),
        ('leads', '0003_alter_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='leads.lead'),
        ),
    ]
