# Generated by Django 6.0.6 on 2026-07-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_assigned_employee_booking_assigned_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('lead', 'Lead'), ('walk_in', 'Walk-in'), ('reference', 'Reference'), ('online', 'Online')], default='walk_in', max_length=20),
        ),
    ]
