# Generated by Django 6.0.6 on 2026-07-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('demand_draft', 'Demand Draft')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
