# Generated by Django 5.2.6 on 2026-07-11 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('commissions', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('booking_source', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ready', 'Ready for Commission'), ('processing', 'In Progress'), ('generated', 'Commission Generated'), ('cancelled', 'Cancelled')], default='ready', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_request', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_requests_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('customer_property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customerproperty')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_requests_generated', to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.plot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
        ),
    ]
