# Generated by Django 5.2.6 on 2026-07-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commissionrequest'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='commissions.commission')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
