# Generated by Django 5.2.6 on 2026-07-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('commissions', '0003_commissionallocation'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionallocation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commissionallocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_allocations', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved'), ('released', 'Released'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='generated', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commission_records', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('customer_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customerproperty')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_commission_records', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commission_records', to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.plot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_commission_records', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='commissions.commissionrequest')),
            ],
        ),
        migrations.AlterField(
            model_name='commissionallocation',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='commissions.commissionrecord'),
        ),
        migrations.CreateModel(
            name='CommissionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('activity', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='commissions.commissionrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
