# Generated by Django 5.2.6 on 2026-07-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('commissions', '0004_commissionallocation_paid_at_and_more'),
        ('customers', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commissionallocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commissionrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commissionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commissiontimeline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='customer_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='customers.customerproperty'),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='projects.plot'),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='record_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='commissiontimeline',
            name='activity',
            field=models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved'), ('released', 'Released'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='generated', max_length=20),
        ),
    ]
