# Generated by Django 5.2.6 on 2026-07-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
